// Domande Jev per cartella clinica - primitive Choice/Score/Noul
export const EHR_QUESTIONS = {
  caduta_presente: { type: "noul", question: "Il testo menziona una caduta del paziente? Cerca caduta, scivolata, inciampato, a terra, caduto." },
  lesione_presente: { type: "noul", question: "C'e' una lesione, piaga da decubito, ulcera, ferita, escoriazione?" },
  lesione_sede: { type: "choice", options: ["sacrale","tallone","trocantere","gomito","nessuna","altro"], question: "Dove e' la lesione?" },
  peso_presente: { type: "noul", question: "Viene menzionato il peso?" },
  peso_valore: { type: "score", min: 20, max: 200, question: "Peso in kg?" },
  temp_presente: { type: "noul", question: "C'e' una temperatura corporea?" },
  temp_valore: { type: "score", min: 35, max: 42, question: "Temperatura in gradi Celsius?" },
  pa_presente: { type: "noul", question: "C'e' pressione arteriosa?" },
  pa_sistolica: { type: "score", min: 70, max: 250, question: "Pressione sistolica?" },
  pa_diastolica: { type: "score", min: 40, max: 150, question: "Pressione diastolica?" },
  fc_presente: { type: "noul", question: "C'e' frequenza cardiaca / battiti?" },
  fc_valore: { type: "score", min: 30, max: 200, question: "Frequenza cardiaca in bpm?" },
  sat_presente: { type: "noul", question: "C'e' saturazione O2?" },
  sat_valore: { type: "score", min: 70, max: 100, question: "Saturazione %?" },
  glicemia_presente: { type: "noul", question: "C'e' glicemia?" },
  glicemia_valore: { type: "score", min: 20, max: 600, question: "Glicemia mg/dL?" },
  dolore_presente: { type: "noul", question: "Viene menzionato dolore?" },
  dolore_valore: { type: "score", min: 0, max: 10, question: "Dolore scala 0-10?" },
};
